// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeYVGFtUPaOBbKlLzbKN7J5dYjf6SzabI',
    appId: '1:54966642500:web:c7301e9b4b43e919a79911',
    messagingSenderId: '54966642500',
    projectId: 'fir-5a8b9',
    authDomain: 'fir-5a8b9.firebaseapp.com',
    storageBucket: 'fir-5a8b9.appspot.com',
    measurementId: 'G-LC57B6TPB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA4P17LivV3IbJOrPERHHKUr0h5-fyBQ8',
    appId: '1:54966642500:android:81a863b2567bc193a79911',
    messagingSenderId: '54966642500',
    projectId: 'fir-5a8b9',
    storageBucket: 'fir-5a8b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABq1rWcpmGwVthUDbRZKjRkwjvHkMd200',
    appId: '1:54966642500:ios:b864e922644697bea79911',
    messagingSenderId: '54966642500',
    projectId: 'fir-5a8b9',
    storageBucket: 'fir-5a8b9.appspot.com',
    iosBundleId: 'com.example.amazon',
  );
}
